### ISSUE TITLE
Error at web Unexpected token 

### ISSUE THREAD

**Issue by otopba** [m-r-davari/flutter_3d_controller#29]
```
model-viewer.min.js:557 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at eh.parse (model-viewer.min.js:515:5223)
    at Object.onLoad (model-viewer.min.js:515:4359)
    at model-viewer.min.js:17:478231
```
    
This is model file:
https://www.dropbox.com/scl/fi/je01232vqyw4srs4j4n7j/shapes_animation_copy.gltf?rlkey=40vh17yv3y5yl0hk9mu4avhkx&dl=0

**Comment by m-r-davari** [comment]
[check out v2.0.0 Installation](https://pub.dev/packages/flutter_3d_controller)
